# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assignments', '0001_initial'),
        ('submissions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGradingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('rubric_breakdown', models.JSONField(default=dict, help_text='{"mantiq": 2, "til": 4, "mosligi": 3}', verbose_name="Rubrika bo'yicha")),
                ('confidence', models.DecimalField(decimal_places=3, default=0.0, max_digits=4, verbose_name='AI ishonch darajasi')),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_grades', to='assignments.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_grades', to='submissions.assignmentsubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'AI baholash natijasi',
                'verbose_name_plural': 'AI baholash natijalari',
                'db_table': 'ai_grading_results',
            },
        ),
        migrations.CreateModel(
            name='TeacherEvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('syllabus_match_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Sillabusga moslik %')),
                ('topics_covered', models.PositiveSmallIntegerField(default=0, verbose_name='Yoritilgan mavzular soni')),
                ('topics_out_of_syllabus', models.PositiveSmallIntegerField(default=0, verbose_name='Sillabusdan tashqarida mavzular')),
                ('question_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI izohi (kafedra uchun)')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_evaluations', to='assignments.assignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': "O'qituvchi baholash jurnali",
                'verbose_name_plural': "O'qituvchi baholash jurnallari",
                'db_table': 'teacher_evaluation_logs',
            },
        ),
        migrations.CreateModel(
            name='TeacherGradeOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(verbose_name="O'zgartirish sababi")),
                ('overridden_at', models.DateTimeField(auto_now_add=True)),
                ('ai_grading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_override', to='grading.aigradingresult')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_overrides', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': "Baho o'zgartirishi",
                'db_table': 'teacher_grade_overrides',
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.PositiveSmallIntegerField(choices=[(2, '2 (Qoniqarsiz)'), (3, '3 (Qoniqarli)'), (4, '4 (Yaxshi)'), (5, "5 (A'lo)")])),
                ('is_confirmed', models.BooleanField(default=False, verbose_name="O'qituvchi tasdiqladi")),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='assignments.assignment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gradebook_entries', to='academics.subjectassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Jurnal yozuvi',
                'verbose_name_plural': 'Jurnal',
                'db_table': 'gradebook',
                'indexes': [models.Index(fields=['student', 'subject_assignment'], name='gradebook_student_80b448_idx')],
                'unique_together': {('subject_assignment', 'student', 'assignment')},
            },
        ),
    ]
