# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Topshirilmagan'), ('started', 'Boshlangan'), ('submitted', 'Topshirilgan'), ('graded', 'Baholangan'), ('expired', "Muddati o'tgan")], default='assigned', max_length=15)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.JSONField(default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_reason', models.TextField(blank=True)),
                ('tab_switch_count', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Topshiriq javobi',
                'verbose_name_plural': 'Topshiriq javoblari',
                'db_table': 'assignment_submissions',
            },
        ),
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab almashtirildi'), ('screen_share', 'Ekran ulashildi'), ('fast_answer', 'Juda tez javob (copy-paste shubhasi)'), ('multi_ip', 'Bir vaqtda ikki joydan kirish'), ('copy_paste', "Nusxa olish/qo'yish"), ('blur', 'Brauzer fokusdan chiqdi')], max_length=20)),
                ('event_data', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori')], default='low', max_length=10)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_cheat_logs', to='submissions.assignmentsubmission')),
            ],
            options={
                'verbose_name': 'Anti-cheat hodisa',
                'verbose_name_plural': 'Anti-cheat hodisalar',
                'db_table': 'anti_cheat_logs',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True, verbose_name='Yozma javob')),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='submission_files/', verbose_name='Yuklangan fayl')),
                ('voice_answer', models.FileField(blank=True, null=True, upload_to='submission_voice/', verbose_name='Ovozli javob')),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('time_spent_seconds', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='assignments.question')),
                ('selected_options', models.ManyToManyField(blank=True, to='assignments.answeroption', verbose_name='Tanlangan variantlar')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='submissions.assignmentsubmission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Savol javobi',
                'verbose_name_plural': 'Savol javoblari',
                'db_table': 'submission_answers',
            },
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['student', 'status'], name='assignment__student_e9c2f6_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'status'], name='assignment__assignm_68808b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AddIndex(
            model_name='anticheatlog',
            index=models.Index(fields=['submission', 'severity'], name='anti_cheat__submiss_14fd2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionanswer',
            unique_together={('submission', 'question')},
        ),
    ]
