# Generated by Django 6.0.6 on 2026-06-28 16:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Tashkilot nomi')),
                ('short_name', models.CharField(max_length=50, verbose_name='Qisqa nomi')),
                ('subdomain', models.CharField(max_length=100, unique=True, verbose_name='Subdomain')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('max_users', models.PositiveIntegerField(default=1000)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('syllabus_match_threshold', models.PositiveSmallIntegerField(default=75)),
                ('grading_sensitivity', models.PositiveSmallIntegerField(default=7)),
                ('inclusive_education_enabled', models.BooleanField(default=True)),
                ('voice_grading_enabled', models.BooleanField(default=True)),
                ('auto_gradebook_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenantlar',
                'db_table': 'tenants',
            },
        ),
    ]
