# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, verbose_name='Topshiriq nomi')),
                ('description', models.TextField(blank=True)),
                ('assignment_type', models.CharField(choices=[('test', 'Test'), ('written', 'Yozma ish'), ('file', 'Fayl topshiriq')], max_length=10, verbose_name='Topshiriq turi')),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vaqt (daqiqa)')),
                ('start_datetime', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('end_datetime', models.DateTimeField(verbose_name='Tugash vaqti')),
                ('total_questions', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jami savollar soni')),
                ('shuffle_questions', models.BooleanField(default=True, verbose_name='Savollarni aralashtirish')),
                ('show_result_immediately', models.BooleanField(default=False)),
                ('allowed_file_types', models.CharField(blank=True, help_text='pdf,docx,jpg (vergul bilan)', max_length=200, verbose_name='Ruxsat etilgan fayl turlari')),
                ('max_file_size_mb', models.PositiveSmallIntegerField(default=10)),
                ('is_inclusive', models.BooleanField(default=False, verbose_name="Ko'zi ojizlar uchun ovozli")),
                ('is_published', models.BooleanField(default=False)),
                ('ai_relevance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='AI sillabusga moslik %')),
                ('ai_relevance_feedback', models.TextField(blank=True, verbose_name='AI izohi')),
                ('ai_checked_at', models.DateTimeField(blank=True, null=True)),
                ('subject_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subjectassignment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriqlar',
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name="Bo'lim nomi")),
                ('questions_count', models.PositiveSmallIntegerField(default=5, verbose_name="Bu bo'limdan nechta savol")),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assignments.assignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.syllabustopic', verbose_name='Mavzu')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'db_table': 'assignment_sections',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('question_type', models.CharField(choices=[('single_choice', 'Bir javobli test'), ('multiple_choice', "Ko'p javobli test"), ('open_ended', 'Ochiq savol')], default='single_choice', max_length=20)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Ball')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('media', models.FileField(blank=True, null=True, upload_to='questions/media/')),
                ('is_tts_readable', models.BooleanField(blank=True, null=True, verbose_name="Ovozda o'qish mumkin")),
                ('tts_text', models.TextField(blank=True, verbose_name='AI tozalangan ovoz matni')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='assignments.assignmentsection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'db_table': 'questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_text', models.TextField(verbose_name='Variant matni')),
                ('is_correct', models.BooleanField(default=False)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_tts_readable', models.BooleanField(blank=True, null=True)),
                ('tts_text', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assignments.question')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'db_table': 'answer_options',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['subject_assignment', 'is_published'], name='assignments_subject_52e9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='assignments_start_d_8ddd43_idx'),
        ),
    ]
