# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('syllabus', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('users', 'Foydalanuvchilar'), ('students', 'Talabalar'), ('teachers', "O'qituvchilar"), ('groups', 'Guruhlar'), ('questions', 'Savollar')], max_length=20)),
                ('file', models.FileField(upload_to='imports/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('processing', 'Jarayonda'), ('done', 'Bajarildi'), ('failed', 'Xato')], default='processing', max_length=15)),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Import jurnali',
                'db_table': 'bulk_import_logs',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('options', models.JSONField(default=list, help_text='[{"text": "...", "is_correct": true}]')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('avg_correct_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="O'rtacha to'g'ri javob %")),
                ('is_duplicate', models.BooleanField(default=False)),
                ('similarity_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='question_bank.questionbank')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='syllabus.syllabustopic')),
            ],
            options={
                'verbose_name': 'Savol banki',
                'db_table': 'question_bank',
                'indexes': [models.Index(fields=['teacher', 'subject'], name='question_ba_teacher_681e1b_idx'), models.Index(fields=['is_duplicate'], name='question_ba_is_dupl_d9e567_idx')],
            },
        ),
    ]
