# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('snapshot_type', models.CharField(choices=[('daily_summary', 'Kunlik xulosa'), ('teacher_performance', "O'qituvchi samaradorligi"), ('student_progress', 'Talaba progressi'), ('department_stats', 'Kafedra statistikasi')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'indexes': [models.Index(fields=['tenant', 'snapshot_date'], name='analytics_s_tenant__3f3559_idx')],
                'unique_together': {('tenant', 'snapshot_date', 'snapshot_type')},
            },
        ),
    ]
