# Generated by Django 6.0.6 on 2026-06-28 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabuses/', verbose_name='Sillabus fayli (PDF/DOCX)')),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('parsed_text', models.TextField(blank=True, verbose_name="AI o'qigan matn")),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('subject_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='academics.subjectassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Sillabus',
                'verbose_name_plural': 'Sillabuslар',
                'db_table': 'syllabuses',
            },
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic_number', models.PositiveSmallIntegerField(verbose_name='Mavzu raqami')),
                ('title', models.CharField(max_length=500, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True)),
                ('week_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hours', models.PositiveSmallIntegerField(default=2)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.syllabus')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
                'db_table': 'syllabus_topics',
                'ordering': ['topic_number'],
            },
        ),
    ]
